---
- name: install apache2
  apt:
    name: apache2
    state: present    # or  state: latest
    update_cache: yes

- name: deploy index
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: starting apache2
  service:
    name: apache2
    state: started
    enabled: yes
